/**
 * Brand Database
 * Comprehensive database of heritage boot and shoe makers.
 */

export interface BrandProfile {
  id: string;
  name: string;
  country: string;
  founded: number;
  location: string;
  category: 'heritage' | 'workwear' | 'dress' | 'lifestyle';
  priceRange: '$' | '$$' | '$$$' | '$$$$';
  construction: string[];
  popularModels: string[];
  leathers: string[];
  description: string;
  knownFor: string;
}

export const BRAND_DATABASE: BrandProfile[] = [
  {
    id: 'red_wing',
    name: 'Red Wing',
    country: 'USA',
    founded: 1905,
    location: 'Red Wing, Minnesota',
    category: 'heritage',
    priceRange: '$$',
    construction: ['Goodyear Welt', 'Puritan Stitch'],
    popularModels: ['Iron Ranger 8111', 'Moc Toe 875', 'Blacksmith 3345', 'Beckman', 'Classic Chelsea'],
    leathers: ['Amber Harness', 'Copper Rough & Tough', 'Oro Legacy', 'Black Prairie', 'Teak Featherstone'],
    description: 'The gateway into heritage boots for most enthusiasts. Red Wing Heritage produces American-made boots using their own S.B. Foot Tanning leather. Known for rugged build quality at an accessible price point.',
    knownFor: 'Best entry-level heritage boots, iconic Americana styling',
  },
  {
    id: 'viberg',
    name: 'Viberg',
    country: 'Canada',
    founded: 1931,
    location: 'Victoria, British Columbia',
    category: 'heritage',
    priceRange: '$$$$',
    construction: ['Stitchdown', 'Goodyear Welt'],
    popularModels: ['Service Boot', 'Derby Boot', 'Chelsea', 'Slipper', 'Country Boot'],
    leathers: ['Chromexcel', 'Shell Cordovan', 'Shinki Horsehide', 'Dublin', 'Calf'],
    description: 'Premium Canadian bootmaker known for refined silhouettes and an obsessive attention to last design. The 2030 last is considered one of the best service boot lasts ever made. Viberg uses exotic leathers and limited-run makeups.',
    knownFor: 'Best service boot silhouette, premium leather selection, limited makeups',
  },
  {
    id: 'alden',
    name: 'Alden',
    country: 'USA',
    founded: 1884,
    location: 'Middleborough, Massachusetts',
    category: 'dress',
    priceRange: '$$$',
    construction: ['Goodyear Welt', 'Stitch-and-Turn'],
    popularModels: ['Indy 403', 'Color #8 Shell LWB', 'Plain Toe Blucher', 'NST Boot', 'Captoe Boot'],
    leathers: ['Shell Cordovan', 'Chromexcel', 'Calfskin', 'Alpine Grain', 'Suede'],
    description: 'The king of shell cordovan footwear. Alden is the premier American dress shoe and boot maker, famous for their Indy boot (worn by Indiana Jones) and their exclusive relationship with Horween shell cordovan.',
    knownFor: 'Shell cordovan mastery, Indy boot, classic American dress shoes',
  },
  {
    id: 'nicks',
    name: "Nicks Handmade Boots",
    country: 'USA',
    founded: 1964,
    location: 'Spokane, Washington',
    category: 'workwear',
    priceRange: '$$$',
    construction: ['Handwelted', 'Stitchdown'],
    popularModels: ['Robert', 'Falcon', 'Traveler', 'Urban Logger', 'Builder Pro'],
    leathers: ['Seidel 1964', 'Chromexcel', 'Waxed Flesh', 'Roughout', 'Bison'],
    description: "True handmade heritage. Every pair of Nicks is built by a single craftsman from start to finish. Originally made for Pacific Northwest loggers, now beloved by heritage enthusiasts. Fully customizable with dozens of leather and hardware options.",
    knownFor: 'Fully handmade, one-craftsman builds, extreme durability, PNW logger heritage',
  },
  {
    id: 'whites',
    name: "White's Boots",
    country: 'USA',
    founded: 1853,
    location: 'Spokane, Washington',
    category: 'workwear',
    priceRange: '$$$',
    construction: ['Handwelted', 'Stitchdown'],
    popularModels: ['Semi-Dress', 'Bounty Hunter', 'MP Sherman', 'Smoke Jumper', 'Hathorn'],
    leathers: ['British Tan', 'Distressed Roughout', 'Chromexcel', 'Waxed Flesh', 'Water Buffalo'],
    description: "America's oldest continuously operating bootmaker. White's Semi-Dress is considered the gold standard of PNW-style heritage boots. Hand-lasted on original forms with an arch support system that conforms to your foot.",
    knownFor: 'Oldest US bootmaker, legendary Semi-Dress, exceptional arch support',
  },
  {
    id: 'wesco',
    name: 'Wesco',
    country: 'USA',
    founded: 1918,
    location: 'Scappoose, Oregon',
    category: 'workwear',
    priceRange: '$$$',
    construction: ['Stitchdown'],
    popularModels: ['Jobmaster', 'Boss', 'Hendrik', 'Axe Breaker', 'Mister Lou'],
    leathers: ['British Tan Domain', 'Burgundy Domain', 'Black Tie Domain', 'Horsehide', 'Roughout'],
    description: 'Rugged Oregon-made boots built for the toughest conditions. Known for their Jobmaster, the ultimate work boot, and their Mr. Lou engineer boot. Every pair features hand-stitched construction and can be fully customized.',
    knownFor: 'Toughest work boots made, Jobmaster, custom engineer boots',
  },
  {
    id: 'grant_stone',
    name: 'Grant Stone',
    country: 'China/USA Design',
    founded: 2016,
    location: 'Designed in USA, made in Xiamen, China',
    category: 'heritage',
    priceRange: '$$',
    construction: ['Goodyear Welt'],
    popularModels: ['Diesel Boot', 'Ottawa Boot', 'Edward Boot', 'Traveler Penny', 'Cap Toe'],
    leathers: ['Chromexcel', 'French Calfskin', 'Crimson Chromexcel', 'Kudu', 'Shell Cordovan'],
    description: 'Exceptional value in heritage footwear. Grant Stone delivers build quality that rivals boots at 2-3x their price. Their Goodyear welt construction and leather selection punch well above their weight class.',
    knownFor: 'Best value in heritage boots, exceptional finishing for the price',
  },
  {
    id: 'parkhurst',
    name: 'Parkhurst',
    country: 'USA',
    founded: 2018,
    location: 'Williamsburg, Virginia',
    category: 'heritage',
    priceRange: '$$',
    construction: ['Goodyear Welt', '270 Welt'],
    popularModels: ['Allen', 'Richmond', 'Delaware', 'Spruce'],
    leathers: ['Chromexcel', 'Kudu', 'Natural CXL', 'Waxy Commander'],
    description: 'A newer American bootmaker focused on heritage styling with modern construction standards. Known for unique leather selections, including South African kudu, and transparent pricing.',
    knownFor: 'American-made at accessible prices, unique leather selections',
  },
  {
    id: 'truman',
    name: 'Truman Boot Co.',
    country: 'USA',
    founded: 2014,
    location: 'Portland, Oregon',
    category: 'heritage',
    priceRange: '$$$',
    construction: ['Stitchdown', 'Goodyear Welt'],
    popularModels: ['Java Waxed Flesh', 'Coach Rambler', 'Super 8', 'Marrone Horsehide'],
    leathers: ['Waxed Flesh', 'Chromexcel', 'Horsehide', 'Bison', 'Kudu'],
    description: 'Portland-based bootmaker known for bold leather choices and a chunky, rugged aesthetic. Their waxed flesh boots have a devoted following. Small-batch production with frequent limited-edition makeups.',
    knownFor: 'Bold leather choices, chunky rugged aesthetic, waxed flesh expertise',
  },
  {
    id: 'john_lofgren',
    name: 'John Lofgren',
    country: 'Japan',
    founded: 2010,
    location: 'Kumamoto, Japan',
    category: 'heritage',
    priceRange: '$$$$',
    construction: ['Goodyear Welt', 'Handwelted'],
    popularModels: ['Combat Boots', 'Donkey Puncher', 'Engineer', 'Chukka', 'M-43 Service Shoes'],
    leathers: ['Horween CXL', 'Badalassi Carlo', 'Shinki Horsehide', 'French Calfskin'],
    description: 'Japanese-made boots with an obsessive attention to historical accuracy and material quality. John Lofgren recreates classic American military and workwear boot designs with Japanese craftsmanship precision.',
    knownFor: 'Japanese precision, historical accuracy, museum-quality construction',
  },
  {
    id: 'role_club',
    name: 'Role Club / Clinch',
    country: 'Japan',
    founded: 2005,
    location: 'Tokyo, Japan',
    category: 'heritage',
    priceRange: '$$$$',
    construction: ['Handwelted', 'Stitchdown'],
    popularModels: ['Engineer', 'Yeager', 'Jodhpur', 'Graham', 'Mushroom'],
    leathers: ['Horween Shell Cordovan', 'Shinki Horsehide', 'Italian Horsehide', 'Chromexcel'],
    description: "Brass Tokyo's Role Club and Clinch lines represent the pinnacle of Japanese boot craftsmanship. Master bootmaker Yuki Matsuda creates completely handmade boots with extraordinary attention to every detail.",
    knownFor: 'Pinnacle Japanese craftsmanship, fully handmade, shell cordovan engineers',
  },
  {
    id: 'russell_moccasin',
    name: 'Russell Moccasin',
    country: 'USA',
    founded: 1898,
    location: 'Berlin, Wisconsin',
    category: 'heritage',
    priceRange: '$$$',
    construction: ['Moccasin Construction', 'Double Vamp'],
    popularModels: ['South 40', 'PH Safari', 'Zephyr', 'Bird Shooter', 'Thula Thula'],
    leathers: ['Triple Vamp', 'Bison', 'Shrunken Bull', 'Shark', 'Elephant'],
    description: 'Specialty moccasin-constructed boots made in Wisconsin since 1898. Known for exotic leathers and custom fit, Russell builds boots for hunters, outdoorsmen, and heritage enthusiasts who want something truly unique.',
    knownFor: 'Moccasin construction, exotic leathers, custom-fit specialist',
  },
  {
    id: 'crockett_jones',
    name: 'Crockett & Jones',
    country: 'England',
    founded: 1879,
    location: 'Northampton, England',
    category: 'dress',
    priceRange: '$$$',
    construction: ['Goodyear Welt', '360 Welt'],
    popularModels: ['Islay', 'Harlech', 'Coniston', 'Skye', 'Pembroke'],
    leathers: ['Scotch Grain', 'Calfskin', 'Suede', 'Cordovan', 'Shell Cordovan'],
    description: 'Premier English shoemaker from Northampton, the heart of British shoemaking. Known for exceptional finishing and classic British country boot styles. Featured in James Bond films.',
    knownFor: 'British craftsmanship, James Bond connection, Northampton heritage',
  },
  {
    id: 'edward_green',
    name: 'Edward Green',
    country: 'England',
    founded: 1890,
    location: 'Northampton, England',
    category: 'dress',
    priceRange: '$$$$',
    construction: ['Goodyear Welt', 'Handwelted'],
    popularModels: ['Galway', 'Dover', 'Chelsea', 'Cadogan', 'Banbury'],
    leathers: ['Utah Leather', 'Calfskin', 'Suede', 'Delapre', 'Country Calf'],
    description: 'The pinnacle of English shoemaking. Edward Green produces some of the finest dress boots and shoes in the world with hand-burnished finishes and near-perfect construction.',
    knownFor: 'Pinnacle English shoemaking, Galway boot, extraordinary finishing',
  },
  {
    id: 'thorogood',
    name: 'Thorogood',
    country: 'USA',
    founded: 1892,
    location: 'Merrill, Wisconsin',
    category: 'workwear',
    priceRange: '$',
    construction: ['Goodyear Welt', 'Storm Welt'],
    popularModels: ['1892 Beloit', '1892 Dodgeville', 'Moc Toe', 'American Heritage'],
    leathers: ['Chromexcel', 'Tobacco Oil-Tanned', 'Black Walnut', 'Storm Welt'],
    description: 'Wisconsin-made boots offering heritage quality at workwear prices. Their 1892 Heritage line competes directly with Red Wing while their workwear line remains a jobsite staple.',
    knownFor: 'American-made value, Moc Toe alternative to Red Wing',
  },
  {
    id: 'carmina',
    name: 'Carmina',
    country: 'Spain',
    founded: 1866,
    location: 'Inca, Mallorca, Spain',
    category: 'dress',
    priceRange: '$$$',
    construction: ['Goodyear Welt', 'Hand-Welted', 'Norwegian Welt'],
    popularModels: ['Jumper Boot', 'Shell Cordovan PTB', 'Wholecut', 'Chelsea', 'Balmoral Boot'],
    leathers: ['Box Calf', 'Shell Cordovan', 'Suede', 'Country Calf', 'Museum Calf'],
    description: 'Spanish shoemaker offering dress shoes and boots that rival English makers at a more accessible price. Known for a wide variety of lasts and an excellent MTO (made-to-order) program.',
    knownFor: 'Spanish craftsmanship, excellent MTO program, shell cordovan value',
  },
  {
    id: 'grenson',
    name: 'Grenson',
    country: 'England',
    founded: 1866,
    location: 'Rushden, Northamptonshire, England',
    category: 'heritage',
    priceRange: '$$',
    construction: ['Goodyear Welt', 'Storm Welt'],
    popularModels: ['Fred', 'Archie', 'Stanley', 'Nanette', 'Brady'],
    leathers: ['Calfskin', 'Suede', 'Hand-Painted Leather', 'Grain Leather', 'Pebble Grain'],
    description: 'One of the oldest English shoemakers, Grenson has been producing Goodyear-welted footwear since 1866. Known for blending traditional Northamptonshire craftsmanship with modern design. Their factory in Rushden is one of the last remaining in the region.',
    knownFor: 'English heritage with modern design, triple-welted boots, Northamptonshire craftsmanship',
  },
  {
    id: 'trickers',
    name: "Tricker's",
    country: 'England',
    founded: 1829,
    location: 'Northampton, England',
    category: 'heritage',
    priceRange: '$$$',
    construction: ['Goodyear Welt', 'Storm Welt', 'Bench-Made'],
    popularModels: ['Stow', 'Bourton', 'Malton', 'Grassmere', 'Ethan'],
    leathers: ['Calfskin', 'Scotch Grain', 'Suede', 'Repello Suede', 'Cavalier Calf'],
    description: "England's oldest shoemaker still operating from their original Northampton factory. Tricker's is synonymous with the classic English country boot. Their Stow brogue boot is an icon of British country style, built to last generations.",
    knownFor: 'Oldest English shoemaker, iconic Stow country boot, heavy-duty bench-made construction',
  },
];

export const BRAND_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'heritage', label: 'Heritage' },
  { id: 'workwear', label: 'Workwear' },
  { id: 'dress', label: 'Dress' },
] as const;

export const BRAND_COUNTRIES = [
  'All',
  'USA',
  'Canada',
  'Japan',
  'England',
  'Spain',
  'China/USA Design',
] as const;
